tap 'homebrew/bundle'
tap 'buo/cask-upgrade'
brew 'mas'

# Binaries
brew 'airspy'
brew 'antidote'
brew 'bash'
brew 'cmake'
brew 'cocoapods'
brew 'coreutils'
brew 'dnsmasq'
brew 'esptool'
brew 'fastlane'
brew 'ffmpeg'
brew 'git'
brew 'httpie'
brew 'mitmproxy'
brew 'libusb'
brew 'neovim'
brew 'nmap'
brew 'node'
brew 'nss'
brew 'openjdk'
brew 'pipx'
brew 'pnpm'
brew 'poetry'
brew 'pwgen'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'rtl-sdr'
brew 'ruff-lsp'
brew 'sherlock'
brew 'sshfs'
brew 'uv'
brew 'vim'
brew 'watchman'
brew 'yt-dlp'
brew 'zellij'
brew 'zsh'

# fzf.vim
brew 'fzf'
brew 'bat'
brew 'ripgrep'
brew 'the_silver_searcher'
brew 'perl'
brew 'universal-ctags'

# Fonts
cask 'font-jetbrains-mono'
cask 'font-meslo-for-powerlevel10k'

# Apps
cask '1password'
cask '1password-cli'
cask 'anaconda'
cask 'android-studio'
cask 'darktable'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'ghostty'
cask 'gqrx'
cask 'macfuse'
cask 'omnissa-horizon-client'
cask 'plex'
cask 'postman'
cask 'pycharm'
cask 'tableplus'
cask 'vlc'
cask 'webstorm'
cask 'wireshark-app'

# Mac App Store
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
mas "Wireguard", id: 1451685025
