call plug#begin($HOME."/.vim/plugged")
Plug 'tpope/vim-vinegar'
Plug 'gruvbox-community/gruvbox'
call plug#end()

runtime macros/matchit.vim

set autoindent
set backspace=indent,eol,start
set incsearch
set ruler
set wildmenu
set number
set numberwidth=5

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

let g:gruvbox_italic=1
let g:gruvbox_number_column='dark0_hard'
colorscheme gruvbox
