" vim:foldmethod=marker:foldlevel=0:foldenable
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-vinegar'
Plug 'gruvbox-community/gruvbox'
Plug 'ludovicchabant/vim-gutentags'
Plug 'janko/vim-test'
Plug 'tpope/vim-dispatch'
Plug 'arnaud-lb/vim-php-namespace'
Plug 'editorconfig/editorconfig-vim'
Plug 'w0rp/ale'
Plug 'SirVer/ultisnips'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()

runtime macros/matchit.vim

set autoindent
set backspace=indent,eol,start
set incsearch
set ruler
set wildmenu
set wildmode=list:full
set wildignorecase
set number
set numberwidth=5
set laststatus=2
set modelines=5
set nowrap

set shiftwidth=4
set softtabstop=4
set expandtab

set backup
set noswapfile
set undodir=~/.vim/tmp/undo//
set backupdir=~/.vim/tmp/backup//
set autowrite
set hidden

let g:gruvbox_italic=1
let g:gruvbox_number_column='dark0_hard'
colorscheme gruvbox

let mapleader=","

" {{{ wildignore
set wildignore+=*/.git/*
set wildignore+=*/node_modules/*
" }}}

" vim-dispatch {{{
let g:dispatch_compilers = {
  \ './bin/phpunit': 'phpunit',
  \ './vendor/bin/phpunit': 'phpunit',
  \}
" }}}

" vim-test {{{
let test#strategy="dispatch"
nnoremap <silent> <leader>tn :TestNearest<cr>
nnoremap <silent> <leader>tf :TestFile<cr>
nnoremap <silent> <leader>ts :TestSuite<cr>
nnoremap <silent> <leader>tl :TestLast<cr>
nnoremap <silent> <leader>tv :TestVisit<cr>
" }}}

" vim-php-namespace {{{
let g:php_namespace_sort_after_insert = 1
let g:php_namespace_sort = "'{,'}-1 ! awk '{ print length(), $0 | \"sort -n | cut -d\\\\  -f2-\" }'"
"}}}

"{{{ ale
let g:ale_fixers = {
    \'javascript': ['eslint'],
    \}

let g:ale_fix_on_save = 1
"}}}

"{{{ ultisnips
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-b>'
let g:UltiSnipsJumpBackwardTrigger='<c-z>'
let g:UltiSnipsEditSplit='vertical'
"}}}

" {{{ maps
" quickly exit insert mode
inoremap jj <esc>

" goto buffer
" open buffer list and prompt for buffer #/name to enter
nnoremap gb :ls<cr>:b<space>

" toggle fold
nnoremap <space> za

" toggle quickfix window
nnoremap <leader>q :call ToggleQuickfixList()<cr>
" }}}
