" XDG
silent !mkdir -p $XDG_CACHE_HOME/vim/swap
silent !mkdir -p $XDG_CACHE_HOME/vim/backup
silent !mkdir -p $XDG_CACHE_HOME/vim/undo
silent !mkdir -p $XDG_CONFIG_HOME/vim/after
set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME,/opt/homebrew/opt/fzf

let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" Install vim-plug if not installed
if empty(glob("$XDG_CONFIG_HOME/vim/autoload/plug.vim"))
  silent execute "!curl -fLo $XDG_CONFIG_HOME/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install plugins
call plug#begin("$XDG_CONFIG_HOME/vim/plugged")
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-vinegar'
call plug#end()

" Enabling filetype support provides filetype-specific indenting,
" syntax highlighting, omni-completion and other useful settings.
filetype plugin indent on
syntax on

" `matchit.vim` is built-in so let's enable it!
" Hit `%` on `if` to jump to `else`.
runtime macros/matchit.vim

" various settings
set autoindent                 " Minimal automatic indenting for any filetype.
set backspace=indent,eol,start " Intuitive backspace behavior.
set hidden                     " Possibility to have more than one unsaved buffers.
set incsearch                  " Incremental search, hit `<CR>` to stop.
set ruler                      " Shows the current line number at the bottom-right
                               " of the screen.
set wildmenu                   " Great command-line completion, use `<Tab>` to move
                               " around and `<CR>` to validate.
set visualbell                 " Display visual bell
set noerrorbells               " Do not play audible bells

" indenting
set softtabstop=4
set tabstop=4
set shiftwidth=4
set noexpandtab                " Use tabs not spaces
set autoindent                 " Inherit indentation from previous line

" quickly exit insert mode
inoremap jj <esc>

" cursor
let &t_SI = "\e[3 q"   " cursor in insert mode
let &t_EI = "\e[2 q"   " cursor in normal mode
let &t_SR = "\e[3 q"   " cursor in replace mode
let &t_ti .= "\e[2 q"  " cursor when vim starts
let &t_te .= "\e[3 q"  " cursor when vim exits
